### ISSUE TITLE
Please publish new version to pypi

### ISSUE THREAD

**Issue by IlyaSemenov** [egregors/django-cbrf#10]
pypi version hasn't been updated since 2019. Can we have the laster master (compatible with Django 4) published to pypi? Thank you.

**Comment by egregors** [comment]
Sure, I'll make a new release this weekend

**Comment by egregors** [comment]
@IlyaSemenov 
Made some cleanup, drop old stuff, and now we are here: https://pypi.org/project/django-cbrf/1.0.0/
